baseURL = "gallant-almeida-33b16a.netlify.com"
languageCode = "en-us"
theme = "hyde"
title = "Fatime Rrahmani"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
